### ISSUE TITLE
Tag a release version

### ISSUE THREAD

**Issue by SvenRtbg** [wepay/PHP-SDK#17]
Tagging a version allows Composer users to use this SDK in a defined, stable version instead of relying on a branch that might be developed adding incompatible features.

It also allows other packages to use this SDK as their dependency without the hassle of not being able to install that package somewhere else if the user does not lower their stability level to "dev".

Please tag a version. You already have a version in your class constant WePay::VERSION, should be a no-brainer.

**Comment by skyzyx** [comment]
Done. Tagged `0.2.5`.

**Comment by SvenRtbg** [comment]
Thanks for making PHP packages easier to use. :)
