### ISSUE TITLE
/account/get_update_uri

### ISSUE THREAD

**Issue by onmountain** [wepay/PHP-SDK#21]
The account_uri  gives me an error. I have to add some code like the following in order to get a link that works:

			// call api to get the wepay update link for the account, in iframe
			$theuri2account = $wepay->request('account/get_update_uri', array( 
				  'account_id' => $account->account_id,
  					'mode' =>'iframe'
			));

**Comment by ellardli** [comment]
Heya,

Do you have the error that the API returned? What was the original code that you had before the changes?

Thanks.

**Comment by skyzyx** [comment]
Resolving due to abandonment.
